# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33ab148a3c42e96a51027f74691b0c2dcd7dff59381c2af32a25d7c0bde25b4459e085f4a7c4d737681b97507b16553d4c85f71b6cfb3533abd87865ec616258

test:
  secret_key_base: 796ef77d82af5720741d2f8b3899fdeeae8c8d6876405a16ea8261019998f9e5ed611d30c033edebd87d630332ccfe4bb41ad5f1eb4411954e04c21e51cd1749

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  TEST_VARIABLE: 'GET_ME'